### ISSUE TITLE
The image mark could support the stroke property

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1464]
I can approximate stroked images using CSS outline (and border-radius):

<img width="705" alt="Screenshot 2023-04-18 at 3 18 39 PM" src="https://user-images.githubusercontent.com/230541/232917470-841d5afc-72bc-4abb-afd4-d98d420b01f1.png">

```css
image {
  outline: solid 1px black;
  border-radius: 100%;
}
```

But it’d be nicer if the image mark interleaved SVG circle elements on top of each image element if you have a stroke.
